Tests
webpush-channels/webpush-channels pull request #6
Opened 2017-01-11 15:52 UTC by mansimarkaur

tries to fix issue #5 
r? @Natim

2017-01-11 15:52 UTC, mansimarkaur commented
On running `make tests-once`,
I'm getting the following error:
```
webpush_channels/tests/test_views_hello.py:5: in <module>
    class HelloViewTest(BaseWebTest, unittest.TestCase):
webpush_channels/tests/test_views_hello.py:9: in HelloViewTest
    self.assertEqual(response.json['version'], VERSION)
E   NameError: name 'self' is not defined
```

2017-01-11 15:55 UTC, Natim commented on MANIFEST.in
> +include *.rst Makefile
We should rather create the LICENCE file.

2017-01-11 15:56 UTC, Natim commented on setup.cfg
> +universal=1
Missing an empty line at the end of the file

2017-01-11 15:56 UTC, Natim commented on webpush_channels/__init__.py
> +	'kinto.core.paginate_by': 100,
tabs vs spaces?

2017-01-11 15:57 UTC, mansimarkaur commented on setup.cfg
> +universal=1
Why is an empty line at the end of the file important?

2017-01-11 15:57 UTC, mansimarkaur commented on MANIFEST.in
> +include *.rst Makefile
Which license do you suggest we use?

2017-01-11 16:01 UTC, Natim requested changes

2017-01-11 16:01 UTC, Natim commented on webpush_channels/__init__.py
> +    'project_docs': 'https://kinto.readthedocs.io/',
Don't seems accurate.

2017-01-11 16:01 UTC, Natim commented on webpush_channels/__init__.py
> +    'permissions_read_principals': Everyone,
We probably don't need that.

2017-01-11 16:01 UTC, Natim commented on webpush_channels/__init__.py
> +    'http_api_version': API_VERSION
I don't think this is the proper `HTTP_API_VERSION` tbh

2017-01-11 16:01 UTC, Natim commented on webpush_channels/tests/test_views_hello.py
> +	def test_returns_info_about_url_and_version(self):
identation problems.

2017-01-11 16:02 UTC, Natim commented on MANIFEST.in
> +include *.rst Makefile
Probably the same as we use for Kinto. https://github.com/Kinto/kinto/blob/master/LICENSE
Apache 2

2017-01-11 16:02 UTC, Natim commented on setup.cfg
> +universal=1
Because Unix tools are looking for it.

Try to do a `cat` on a file with and without the line for instance :)

2017-01-11 16:49 UTC, mansimarkaur commented on webpush_channels/__init__.py
> +    'permissions_read_principals': Everyone,
You mean the 'permission_read_principals' is not needed?

2017-01-11 18:23 UTC, Natim commented on webpush_channels/__init__.py
> +HTTP_API_VERSION = '1.14'
Let's start with 0.1 maybe we can increase it with time 👍

2017-01-11 18:23 UTC, Natim commented on webpush_channels/__init__.py
> +	'kinto.core.paginate_by': 100,
Actually we should use 4 spaces.

2017-01-11 18:34 UTC, mansimarkaur commented on webpush_channels/__init__.py
> +HTTP_API_VERSION = '1.14'
Sure.

2017-01-16 16:03 UTC, Natim requested changes
Wow you did a bunch of good things here :)

2017-01-16 16:03 UTC, Natim commented on .travis.yml
> +    - ACTION=loadtest
I don't think we need to keep that.

2017-01-16 16:03 UTC, Natim commented on MANIFEST.in
> +
Why is there two empty lines at the end?

2017-01-16 16:03 UTC, Natim commented on README.rst
> +
Why is there two empty lines at the end?

2017-01-16 16:03 UTC, Natim commented on setup.cfg
> +
Why is there two empty lines at the end?

2017-01-16 16:03 UTC, Natim commented on webpush_channels/__init__.py
> +	'kinto.core.paginate_by': 100,
The indentation level is not correct here.

2017-01-16 16:03 UTC, Natim commented on webpush_channels/__init__.py
> +	if not config:
The indentation is not correct.

2017-01-16 16:03 UTC, Natim commented on webpush_channels/tests/test_subscription_schema.py
> +				p256dh="encryptionKey")
incorrect Indentation

2017-01-16 16:03 UTC, Natim commented on webpush_channels/tests/test_subscription_schema.py
> +        			keys=keys)
Incorrect indentation.

2017-01-16 16:19 UTC, mansimarkaur commented on .travis.yml
> +    - ACTION=loadtest
So, we don't need to mention any env section?

2017-01-16 16:23 UTC, Natim commented on .travis.yml
> +    - ACTION=loadtest
Oh sorry no just the loadtest one.

2017-01-16 16:55 UTC, Natim commented on webpush_channels/__init__.py
> +			    version=__version__,
Still a wrong indentation there, should be space and the config should be aligned with version and default_settings

2017-01-16 16:55 UTC, Natim commented on webpush_channels/views/subscriptions.py
> +	  collection_path='/subscriptions',
Please remove all the tabs everywhere.

2017-01-16 16:56 UTC, mansimarkaur commented on .travis.yml
> +    - ACTION=loadtest
Okay. Thanks.

2017-01-16 17:00 UTC, Natim commented on webpush_channels/__init__.py
> +		'kinto.authorization.AuthorizationPolicy'),
Apparently there are still some tabs there :)

2017-01-16 17:01 UTC, Natim commented on webpush_channels/__init__.py
> +			    version=__version__,
Apparently there are still some tabs there :)

2017-01-16 17:01 UTC, Natim requested changes
Still few nits

2017-01-16 17:01 UTC, Natim commented on webpush_channels/tests/test_views_hello.py
> +                        'http://webpush-channels-broadcasting.readthedocs.io/')
One space missing here.

2017-01-16 17:01 UTC, Natim commented on webpush_channels/views/subscriptions.py
> +	  collection_path='/subscriptions',
One space missing here and below

2017-01-17 08:47 UTC, Natim commented on Makefile
> +    @echo "Please use 'make <target>' where <target> is one of"
Actually we should not change tabs with space in the Makefile because the makefile only works with tabs. Did you try it?

2017-01-17 08:49 UTC, Natim approved these changes

2017-01-17 08:49 UTC, merged